server:
  port: 8080
  auth: true
  token: 123456

devices:
  - name: 我的电脑1
    ip: 192.168.1.240
    mac: 4C-10-D5-81-CF-EsF
    username: winrm
    password: 806906623
    delay: 10

  - name: 我的电脑2
    ip: 192.168.1.2
    mac: 00:00:00:00:00:02
    username: winrm
    password: 806906623
    delay: 20

  - name: Test
    ip: 192.168.1.3
    mac: 00:00:00:00:00:03
    username: winrm
    password: 806906623
    delay: 20